Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -39,7 +39,7 @@ jobs:
           source ~/.bashrc
           conda activate Forest_Cover_Classification
           pip install mlflow
-          pip install -r MLProject/requirements.txt
+          pip install -r MLProject/requirements.txt || echo "No additional requirements"
 
       - name: 🚀 Run MLflow Project
         run: |
@@ -53,7 +53,7 @@ jobs:
           conda activate Forest_Cover_Classification
           cd MLProject
           echo "Searching for run_name: Hyperparameter_Tuning"
-          RUN_ID=$(grep -l "run_name: Hyperparameter_Tuning" mlruns/0/*/meta.yaml | head -n 1 | cut -d'/' -f2)
+          RUN_ID=$(grep -l "run_name: Hyperparameter_Tuning" mlruns/0/*/meta.yaml | head -n 1 | cut -d'/' -f3)
           echo "Detected RUN_ID=$RUN_ID"
           echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
 
@@ -61,25 +61,26 @@ jobs:
         run: |
           source ~/.bashrc
           conda activate Forest_Cover_Classification
+          cd MLProject
           echo "Artifacts in latest run ($RUN_ID):"
           ls -R mlruns/0/$RUN_ID/artifacts/
-
 
       - name: ✅ Verify model artifacts exist
         run: |
           source ~/.bashrc
           conda activate Forest_Cover_Classification
+          cd MLProject
           echo "Verifying model artifacts for RUN_ID: $RUN_ID"
           ARTIFACT_DIR="mlruns/0/$RUN_ID/artifacts"
           if [ ! -d "$ARTIFACT_DIR/best_model_tuned" ]; then
-          echo "❌ best_model_tuned not found in $ARTIFACT_DIR"
-          exit 1
+            echo "❌ best_model_tuned not found in $ARTIFACT_DIR"
+            exit 1
           fi
           echo "✅ Model artifacts verified."
 
-
       - name: 📤 Commit mlruns to repository
         run: |
+          cd MLProject
           git config --global user.name "${{ secrets.GIT_USERNAME }}"
           git config --global user.email "${{ secrets.GIT_EMAIL }}"
           git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
@@ -93,8 +94,8 @@ jobs:
         run: |
           source ~/.bashrc
           conda activate Forest_Cover_Classification
+          cd MLProject
           mlflow models build-docker --model-uri "file://mlruns/0/$RUN_ID/artifacts/best_model_tuned" --name cc
-
 
       - name: 🔐 Login to Docker Hub
         uses: docker/login-action@v2
@@ -109,4 +110,3 @@ jobs:
       - name: 📦 Push Docker Image to Docker Hub
         run: |
           docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}:latest
-
